# Intel numpy-base is still needed for internal wheels CI, so we control its use with this optional toggle
{% set use_numpy_base = environ.get('USE_NUMPY_BASE', 'true').lower() == 'true' %}

package:
    name: mkl_umath
    version: {{ GIT_DESCRIBE_TAG }}

source:
    path: ../

build:
    number: {{ GIT_DESCRIBE_NUMBER }}
    script_env:
      - WHEELS_OUTPUT_FOLDER
    ignore_run_exports:
      - blas

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}
      - {{ stdlib('c') }}
      - {{ compiler('dpcpp') }} >=2024.2  # [not osx]
    host:
      - setuptools >=77
      - cmake
      - ninja
      - git
      - cython
      - scikit-build
      - python
      - python-gil     # [py>=314]
      - mkl-devel
      {% if use_numpy_base %}
      - numpy-base
      {% else %}
      - numpy
      {% endif %}
      - wheel  >=0.41.3
    run:
      - python
      - python-gil     # [py>=314]
      - {{ pin_compatible('mkl') }}
      - {{ pin_compatible('intel-cmplr-lib-rt') }}
      {% if use_numpy_base %}
      - numpy-base
      {% else %}
      - numpy >=1.26.4
      {% endif %}

test:
    requires:
      - pytest
    source_files:
      - mkl_umath/tests/test_basic.py
    commands:
      - pytest mkl_umath/tests/test_basic.py
    imports:
      - mkl_umath
      - mkl_umath._ufuncs
      - mkl_umath._patch_numpy

about:
    home: http://github.com/IntelPython/mkl_umath
    license: BSD-3-Clause
    license_file: LICENSE.txt
    summary: Universal functions for real and complex floating point arrays powered by Intel(R) Math Kernel Library Vector (Intel(R) MKL) and Intel(R) Short Vector Math Library (Intel(R) SVML)
    description: |
        <strong>LEGAL NOTICE: Use of this software package is subject to the
        software license agreement (as set forth above, in the license section of
        the installed Conda package and/or the README file) and all notices,
        disclaimers or license terms for third party or open source software
        included in or with the software.</strong>
        <br/><br/>
        EULA: <a href="https://opensource.org/licenses/BSD-3-Clause" target="_blank">BSD-3-Clause</a>
        <br/><br/>
